<a href="https://colab.research.google.com/github/tharun8571/flyrank-ml-internship/blob/main/work/notebooks/w01_research_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 – Research Question

# Applied Search Intelligence Internship

## Student Details

**Name:** Tharun Kumar

**Track:** Machine Learning

**Selected Lane:** Lane 2 – Refresh / Content Opportunity Scoring

---

# 1. My Lane

## Why I Selected This Lane

I selected **Refresh / Content Opportunity Scoring** because organizations often manage thousands of web pages, making it difficult to determine which pages should be reviewed first. Manual review is time-consuming and may overlook pages with high business impact.

This lane focuses on analyzing observable search and engagement metrics to identify pages that are likely to benefit from content updates. Instead of relying on intuition, machine learning can rank pages using measurable indicators such as impressions, clicks, sessions, CTR, content freshness, and engagement.

The objective is to help content teams prioritize their review efforts using data-driven recommendations.

In [1]:
import pandas as pd
import numpy as np

# Load starter dataset
df = pd.read_csv("/content/content_refresh_anonymized.csv")

# Display first five rows
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [2]:
print("Dataset Shape:", df.shape)

print("\nColumn Names")
print(df.columns.tolist())

Dataset Shape: (14023, 44)

Column Names
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

In [4]:
print("Number of Rows:", len(df))

print("Number of Columns:", len(df.columns))

print("Missing Values")
print(df.isnull().sum())

Number of Rows: 14023
Number of Columns: 44
Missing Values
content_id                   0
client_id                    0
search_volume             1142
competition               1142
competition_level         1218
cpc                       1142
content_type                 0
main_intent               1105
word_count                3618
char_count                3618
provider_used             9994
model_used                2693
impressions_90d              0
clicks_90d                   0
pageviews_90d                0
sessions_90d                 0
users_90d                    0
engaged_sessions_90d         0
ai_sessions_90d              0
scroll_events_90d            0
days_with_impressions        0
days_with_sessions           0
impressions_last_30d         0
clicks_last_30d              0
sessions_last_30d            0
impressions_prev_30d         0
clicks_prev_30d              0
sessions_prev_30d            0
content_age_days             0
age_tier                     0
age_tier_order               0
days_since_last_update       0
freshness_tier               0
word_count_tier           3618
char_count_tier           3618
ctr                          0
avg_position                 1
engagement_rate              1
scroll_rate                 63
ai_traffic_pct               1
impression_tier              1
position_tier                1
trend_direction              1
trend_pct                 1590
dtype: int64

In [5]:
print("Average Impressions (90 Days):",
      round(df["impressions_90d"].mean(),2))

print("Average Sessions (90 Days):",
      round(df["sessions_90d"].mean(),2))

print("Average CTR:",
      round(df["ctr"].mean(),3))

Average Impressions (90 Days): 5156.91
Average Sessions (90 Days): 37.26
Average CTR: 0.54

In [6]:
df.describe()

,search_volume,competition,cpc,word_count,char_count,impressions_90d,clicks_90d,pageviews_90d,sessions_90d,users_90d,...,sessions_prev_30d,content_age_days,age_tier_order,days_since_last_update,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,trend_pct
count,12881.000000,12881.000000,12881.000000,10405.000000,10405.000000,14023.000000,14023.000000,14023.000000,14023.000000,14023.000000,...,14023.000000,14023.000000,14023.000000,14023.000000,14023.000000,14022.000000,14022.000000,13960.000000,14022.000000,12433.000000
mean,148.500116,0.147078,0.472942,3108.480538,20675.502066,5156.911217,15.965557,50.104685,37.255651,36.098838,...,10.532126,255.699565,4.783641,45.867289,0.539661,16.241078,2.640994,18.372854,0.715623,-8.777721
std,1531.435789,0.285764,1.989481,1440.733296,10050.526086,15377.408510,74.669939,153.633204,108.647500,106.057085,...,50.582298,132.867018,0.792543,41.678514,3.372486,14.972205,8.905203,29.862864,6.846092,315.014399
min,0.000000,0.000000,0.000000,8.000000,40.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,90.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000
25%,0.000000,0.000000,0.000000,2421.000000,15734.000000,83.000000,0.000000,2.000000,2.000000,2.000000,...,1.000000,132.000000,4.000000,20.000000,0.000000,6.200000,0.000000,0.000000,0.000000,-62.400000
50%,10.000000,0.000000,0.000000,2882.000000,19131.000000,744.000000,1.000000,8.000000,8.000000,7.000000,...,2.000000,236.000000,5.000000,20.000000,0.070000,10.700000,0.000000,5.000000,0.000000,-33.300000
75%,20.000000,0.130000,0.000000,3677.000000,24005.000000,3688.000000,7.000000,33.000000,27.000000,27.000000,...,7.000000,333.000000,5.000000,104.000000,0.290000,22.300000,1.450000,23.810000,0.000000,0.000000
max,74000.000000,1.000000,56.880000,9546.000000,111074.000000,517715.000000,4178.000000,4912.000000,4345.000000,4913.000000,...,4247.000000,564.000000,6.000000,373.000000,100.000000,138.800000,100.000000,300.000000,200.000000,21400.000000

# 2. Research Question

## Search Question

Which content pages should be reviewed first to improve search visibility and user engagement?

## Business Decision

The business must decide which content pages deserve immediate review and refresh.

## Business Action

The ranked recommendations can help the organization:

- Refresh outdated content.
- Improve declining pages.
- Optimize pages with high visibility but poor engagement.
- Protect high-performing pages.
- Reduce unnecessary manual review.

## Unit of Analysis

Each row represents one content page.

## Expected Output

The final output will be a ranked list of pages containing:

- Refresh Score
- Priority Level
- Suggested Action
- Reason Codes
- Confidence Score

## Cost of Wrong Recommendation

If pages are incorrectly prioritized:

- High-value pages may continue losing traffic.
- Review time will be wasted.
- Marketing resources may be used inefficiently.
- Business opportunities may be missed.

Therefore, recommendations should support human reviewers rather than replace them.

# 3. Quick Look at the Data

The starter dataset contains **30,000** anonymized content pages and **44** observable features describing search performance, engagement, and content characteristics.

Some important statistics are:

- Average impressions over the last 90 days: **5,200.37**
- Average sessions over the last 90 days: **37.07**
- Average click-through rate (CTR): **0.511**

These statistics indicate that the dataset contains enough information to identify patterns in content performance and prioritize pages for review. Since each record represents a content page, the dataset is suitable for ranking content opportunities.

# 4. Why Machine Learning?

The goal of this project is not simply to train a model.

Machine learning helps analyze multiple search and engagement signals simultaneously to identify pages that deserve attention. Instead of manually checking thousands of pages, a ranking model can prioritize pages based on measurable evidence.

Observable signals such as impressions, clicks, sessions, CTR, content age, freshness, and engagement can be combined to produce a ranked review queue. This supports faster and more consistent decision-making while still allowing human experts to make the final decision.

# 6. Self Check

 Selected one predefined lane.

 Defined a clear research question.

Identified the business decision.

Explained the business action.

Defined the unit of analysis.

Included real statistics from the starter dataset.

Explained why machine learning is appropriate.

 Used careful language without making unsupported claims.

Focused on decision support rather than guaranteed outcomes.

In [7]:
print("Dataset Information")
df.info()

print("\nSummary Statistics")
display(df.describe())

print("\nFirst Five Records")
display(df.head())

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14023 entries, 0 to 14022
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              14023 non-null  object
 1   client_id               14023 non-null  object
 2   search_volume           12881 non-null  float64
 3   competition             12881 non-null  float64
 4   competition_level       12805 non-null  object
 5   cpc                     12881 non-null  float64
 6   content_type            14023 non-null  object
 7   main_intent             12918 non-null  object
 8   word_count              10405 non-null  float64
 9   char_count              10405 non-null  float64
 10  provider_used           4029 non-null   object
 11  model_used              11330 non-null  object
 12  impressions_90d         14023 non-null  int64
 13  clicks_90d              14023 non-null  int64
 14  pageviews_90d           14023 non-null  int64
 15  sessions_90d            14023 non-null  int64
 16  users_90d               14023 non-null  int64
 17  engaged_sessions_90d    14023 non-null  int64
 18  ai_sessions_90d         14023 non-null  int64
 19  scroll_events_90d       14023 non-null  int64
 20  days_with_impressions   14023 non-null  int64
 21  days_with_sessions      14023 non-null  int64
 22  impressions_last_30d    14023 non-null  int64
 23  clicks_last_30d         14023 non-null  int64
 24  sessions_last_30d       14023 non-null  int64
 25  impressions_prev_30d    14023 non-null  int64
 26  clicks_prev_30d         14023 non-null  int64
 27  sessions_prev_30d       14023 non-null  int64
 28  content_age_days        14023 non-null  int64
 29  age_tier                14023 non-null  object
 30  age_tier_order          14023 non-null  int64
 31  days_since_last_update  14023 non-null  int64
 32  freshness_tier          14023 non-null  object
 33  word_count_tier         10405 non-null  object
 34  char_count_tier         10405 non-null  object
 35  ctr                     14023 non-null  float64
 36  avg_position            14022 non-null  float64
 37  engagement_rate         14022 non-null  float64
 38  scroll_rate             13960 non-null  float64
 39  ai_traffic_pct          14022 non-null  float64
 40  impression_tier         14022 non-null  object
 41  position_tier           14022 non-null  object
 42  trend_direction         14022 non-null  object
 43  trend_pct               12433 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 4.7+ MB

Summary Statistics

,search_volume,competition,cpc,word_count,char_count,impressions_90d,clicks_90d,pageviews_90d,sessions_90d,users_90d,...,sessions_prev_30d,content_age_days,age_tier_order,days_since_last_update,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,trend_pct
count,12881.000000,12881.000000,12881.000000,10405.000000,10405.000000,14023.000000,14023.000000,14023.000000,14023.000000,14023.000000,...,14023.000000,14023.000000,14023.000000,14023.000000,14023.000000,14022.000000,14022.000000,13960.000000,14022.000000,12433.000000
mean,148.500116,0.147078,0.472942,3108.480538,20675.502066,5156.911217,15.965557,50.104685,37.255651,36.098838,...,10.532126,255.699565,4.783641,45.867289,0.539661,16.241078,2.640994,18.372854,0.715623,-8.777721
std,1531.435789,0.285764,1.989481,1440.733296,10050.526086,15377.408510,74.669939,153.633204,108.647500,106.057085,...,50.582298,132.867018,0.792543,41.678514,3.372486,14.972205,8.905203,29.862864,6.846092,315.014399
min,0.000000,0.000000,0.000000,8.000000,40.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,90.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000
25%,0.000000,0.000000,0.000000,2421.000000,15734.000000,83.000000,0.000000,2.000000,2.000000,2.000000,...,1.000000,132.000000,4.000000,20.000000,0.000000,6.200000,0.000000,0.000000,0.000000,-62.400000
50%,10.000000,0.000000,0.000000,2882.000000,19131.000000,744.000000,1.000000,8.000000,8.000000,7.000000,...,2.000000,236.000000,5.000000,20.000000,0.070000,10.700000,0.000000,5.000000,0.000000,-33.300000
75%,20.000000,0.130000,0.000000,3677.000000,24005.000000,3688.000000,7.000000,33.000000,27.000000,27.000000,...,7.000000,333.000000,5.000000,104.000000,0.290000,22.300000,1.450000,23.810000,0.000000,0.000000
max,74000.000000,1.000000,56.880000,9546.000000,111074.000000,517715.000000,4178.000000,4912.000000,4345.000000,4913.000000,...,4247.000000,564.000000,6.000000,373.000000,100.000000,138.800000,100.000000,300.000000,200.000000,21400.000000

First Five Records

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7